# This workflow will install Python dependencies, run tests

name: Python project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
       python-version: ${{ matrix.python-version }}
    - name: Install pip dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install test requirements dependencies 
      run: |    
        pip install -r project/requirements/test_requirements.txt
    - name: train pipeline
      run: |
        python project/titanic_model/train_pipeline.py
    - name: test with pytest
      run: |
        pytest
